// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/order/v1/order.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_order_v1_order_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_v1_order_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_order_v1_order_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN             OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLING       OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_OPEN",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELLING",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_OPEN":             1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELLING":       4,
		"ORDER_STATUS_CANCELLED":        5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_v1_order_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_order_v1_order_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{2}
}

type Order struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId  string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"` // e.g. "BTC-USDT"
	Side      OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=tradedrift.order.v1.OrderSide" json:"side,omitempty"`
	OrderType OrderType              `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=tradedrift.order.v1.OrderType" json:"order_type,omitempty"`
	// Decimal string.
	// Required for LIMIT orders.
	// Required for MARKET BUY as maximum acceptable price.
	// Empty for MARKET SELL.
	Price             string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity          string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`                                            // Decimal string (ALWAYS base asset quantity)
	FilledQuantity    string                 `protobuf:"bytes,8,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`          // Decimal string
	RemainingQuantity string                 `protobuf:"bytes,9,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"` // Decimal string
	Status            OrderStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=tradedrift.order.v1.OrderStatus" json:"status,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *Order) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId  string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side      OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=tradedrift.order.v1.OrderSide" json:"side,omitempty"`
	OrderType OrderType              `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=tradedrift.order.v1.OrderType" json:"order_type,omitempty"`
	// Decimal string.
	// Required for LIMIT orders.
	// Required for MARKET BUY as maximum acceptable price.
	// Empty for MARKET SELL.
	Price          string `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       string `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"` // Decimal string (ALWAYS base asset quantity)
	IdempotencyKey string `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=tradedrift.order.v1.OrderSide" json:"side,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=tradedrift.order.v1.OrderStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ListOrdersRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListOrdersRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListOrdersRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// Internal/admin operation used during market halt or system reset.
type CancelAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersRequest) Reset() {
	*x = CancelAllOrdersRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersRequest) ProtoMessage() {}

func (x *CancelAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelAllOrdersRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type CancelAllOrdersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CancelledCount int32                  `protobuf:"varint,1,opt,name=cancelled_count,json=cancelledCount,proto3" json:"cancelled_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelAllOrdersResponse) Reset() {
	*x = CancelAllOrdersResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersResponse) ProtoMessage() {}

func (x *CancelAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelAllOrdersResponse) GetCancelledCount() int32 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

var File_proto_order_v1_order_proto protoreflect.FileDescriptor

const file_proto_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/order/v1/order.proto\x12\x13tradedrift.order.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x122\n" +
	"\x04side\x18\x04 \x01(\x0e2\x1e.tradedrift.order.v1.OrderSideR\x04side\x12=\n" +
	"\n" +
	"order_type\x18\x05 \x01(\x0e2\x1e.tradedrift.order.v1.OrderTypeR\torderType\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12'\n" +
	"\x0ffilled_quantity\x18\b \x01(\tR\x0efilledQuantity\x12-\n" +
	"\x12remaining_quantity\x18\t \x01(\tR\x11remainingQuantity\x128\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2 .tradedrift.order.v1.OrderStatusR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x98\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x122\n" +
	"\x04side\x18\x03 \x01(\x0e2\x1e.tradedrift.order.v1.OrderSideR\x04side\x12=\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2\x1e.tradedrift.order.v1.OrderTypeR\torderType\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"G\n" +
	"\x13CreateOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.tradedrift.order.v1.OrderR\x05order\"H\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x13CancelOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.tradedrift.order.v1.OrderR\x05order\"E\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x10GetOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.tradedrift.order.v1.OrderR\x05order\"\xc1\x02\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x122\n" +
	"\x04side\x18\x03 \x01(\x0e2\x1e.tradedrift.order.v1.OrderSideR\x04side\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .tradedrift.order.v1.OrderStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12.\n" +
	"\x04from\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"i\n" +
	"\x12ListOrdersResponse\x122\n" +
	"\x06orders\x18\x01 \x03(\v2\x1a.tradedrift.order.v1.OrderR\x06orders\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"5\n" +
	"\x16CancelAllOrdersRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"B\n" +
	"\x17CancelAllOrdersResponse\x12'\n" +
	"\x0fcancelled_count\x18\x01 \x01(\x05R\x0ecancelledCount*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*\xb7\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x1b\n" +
	"\x17ORDER_STATUS_CANCELLING\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x052\xf8\x03\n" +
	"\fOrderService\x12`\n" +
	"\vCreateOrder\x12'.tradedrift.order.v1.CreateOrderRequest\x1a(.tradedrift.order.v1.CreateOrderResponse\x12`\n" +
	"\vCancelOrder\x12'.tradedrift.order.v1.CancelOrderRequest\x1a(.tradedrift.order.v1.CancelOrderResponse\x12W\n" +
	"\bGetOrder\x12$.tradedrift.order.v1.GetOrderRequest\x1a%.tradedrift.order.v1.GetOrderResponse\x12]\n" +
	"\n" +
	"ListOrders\x12&.tradedrift.order.v1.ListOrdersRequest\x1a'.tradedrift.order.v1.ListOrdersResponse\x12l\n" +
	"\x0fCancelAllOrders\x12+.tradedrift.order.v1.CancelAllOrdersRequest\x1a,.tradedrift.order.v1.CancelAllOrdersResponseB.Z,tradedrift/platform/api/gen/order/v1;orderv1b\x06proto3"

var (
	file_proto_order_v1_order_proto_rawDescOnce sync.Once
	file_proto_order_v1_order_proto_rawDescData []byte
)

func file_proto_order_v1_order_proto_rawDescGZIP() []byte {
	file_proto_order_v1_order_proto_rawDescOnce.Do(func() {
		file_proto_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_v1_order_proto_rawDesc), len(file_proto_order_v1_order_proto_rawDesc)))
	})
	return file_proto_order_v1_order_proto_rawDescData
}

var file_proto_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_order_v1_order_proto_goTypes = []any{
	(OrderSide)(0),                  // 0: tradedrift.order.v1.OrderSide
	(OrderType)(0),                  // 1: tradedrift.order.v1.OrderType
	(OrderStatus)(0),                // 2: tradedrift.order.v1.OrderStatus
	(*Order)(nil),                   // 3: tradedrift.order.v1.Order
	(*CreateOrderRequest)(nil),      // 4: tradedrift.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),     // 5: tradedrift.order.v1.CreateOrderResponse
	(*CancelOrderRequest)(nil),      // 6: tradedrift.order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),     // 7: tradedrift.order.v1.CancelOrderResponse
	(*GetOrderRequest)(nil),         // 8: tradedrift.order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),        // 9: tradedrift.order.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),       // 10: tradedrift.order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),      // 11: tradedrift.order.v1.ListOrdersResponse
	(*CancelAllOrdersRequest)(nil),  // 12: tradedrift.order.v1.CancelAllOrdersRequest
	(*CancelAllOrdersResponse)(nil), // 13: tradedrift.order.v1.CancelAllOrdersResponse
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_proto_order_v1_order_proto_depIdxs = []int32{
	0,  // 0: tradedrift.order.v1.Order.side:type_name -> tradedrift.order.v1.OrderSide
	1,  // 1: tradedrift.order.v1.Order.order_type:type_name -> tradedrift.order.v1.OrderType
	2,  // 2: tradedrift.order.v1.Order.status:type_name -> tradedrift.order.v1.OrderStatus
	14, // 3: tradedrift.order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: tradedrift.order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: tradedrift.order.v1.CreateOrderRequest.side:type_name -> tradedrift.order.v1.OrderSide
	1,  // 6: tradedrift.order.v1.CreateOrderRequest.order_type:type_name -> tradedrift.order.v1.OrderType
	3,  // 7: tradedrift.order.v1.CreateOrderResponse.order:type_name -> tradedrift.order.v1.Order
	3,  // 8: tradedrift.order.v1.CancelOrderResponse.order:type_name -> tradedrift.order.v1.Order
	3,  // 9: tradedrift.order.v1.GetOrderResponse.order:type_name -> tradedrift.order.v1.Order
	0,  // 10: tradedrift.order.v1.ListOrdersRequest.side:type_name -> tradedrift.order.v1.OrderSide
	2,  // 11: tradedrift.order.v1.ListOrdersRequest.status:type_name -> tradedrift.order.v1.OrderStatus
	14, // 12: tradedrift.order.v1.ListOrdersRequest.from:type_name -> google.protobuf.Timestamp
	14, // 13: tradedrift.order.v1.ListOrdersRequest.to:type_name -> google.protobuf.Timestamp
	3,  // 14: tradedrift.order.v1.ListOrdersResponse.orders:type_name -> tradedrift.order.v1.Order
	4,  // 15: tradedrift.order.v1.OrderService.CreateOrder:input_type -> tradedrift.order.v1.CreateOrderRequest
	6,  // 16: tradedrift.order.v1.OrderService.CancelOrder:input_type -> tradedrift.order.v1.CancelOrderRequest
	8,  // 17: tradedrift.order.v1.OrderService.GetOrder:input_type -> tradedrift.order.v1.GetOrderRequest
	10, // 18: tradedrift.order.v1.OrderService.ListOrders:input_type -> tradedrift.order.v1.ListOrdersRequest
	12, // 19: tradedrift.order.v1.OrderService.CancelAllOrders:input_type -> tradedrift.order.v1.CancelAllOrdersRequest
	5,  // 20: tradedrift.order.v1.OrderService.CreateOrder:output_type -> tradedrift.order.v1.CreateOrderResponse
	7,  // 21: tradedrift.order.v1.OrderService.CancelOrder:output_type -> tradedrift.order.v1.CancelOrderResponse
	9,  // 22: tradedrift.order.v1.OrderService.GetOrder:output_type -> tradedrift.order.v1.GetOrderResponse
	11, // 23: tradedrift.order.v1.OrderService.ListOrders:output_type -> tradedrift.order.v1.ListOrdersResponse
	13, // 24: tradedrift.order.v1.OrderService.CancelAllOrders:output_type -> tradedrift.order.v1.CancelAllOrdersResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_order_v1_order_proto_init() }
func file_proto_order_v1_order_proto_init() {
	if File_proto_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_v1_order_proto_rawDesc), len(file_proto_order_v1_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_v1_order_proto_goTypes,
		DependencyIndexes: file_proto_order_v1_order_proto_depIdxs,
		EnumInfos:         file_proto_order_v1_order_proto_enumTypes,
		MessageInfos:      file_proto_order_v1_order_proto_msgTypes,
	}.Build()
	File_proto_order_v1_order_proto = out.File
	file_proto_order_v1_order_proto_goTypes = nil
	file_proto_order_v1_order_proto_depIdxs = nil
}
