// Package kafka handles the LE's Kafka producer and consumer.
// The producer publishes CommandEnvelope messages to orders.commands.
// The consumer reads TradeExecuted events from trades.executed.
//
// CommandEnvelope schema is defined by the Matching Engine consumer.
// The LE must produce messages that pass ME's validation exactly:
//   - msg.Key == []byte(env.MarketID)          (ME fails-closed otherwise)
//   - env.EventVersion == 1                     (ME rejects other versions)
//   - env.EventID must be a valid UUID
//   - prices must be tick-rounded strings
//   - quantities must be lot-rounded strings
//   - order_id must be a valid UUID
//   - user_id must be "MM-001" (Order Service string identity)
package kafka

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	kafkago "github.com/segmentio/kafka-go"
	"go.uber.org/zap"
)

// Topic constants — must match ME and Order Service topic names.
const (
	TopicOrderCommands  = "orders.commands"
	TopicTradesExecuted = "trades.executed"
)

// CommandEnvelope is the standard message envelope for orders.commands.
type CommandEnvelope struct {
	EventID      string          `json:"event_id"`      // UUIDv4 generated by LE
	EventType    string          `json:"event_type"`    // "OrderCreated" | "OrderCancelRequested"
	EventVersion int             `json:"event_version"` // must be 1
	MarketID     string          `json:"market_id"`     // e.g. "BTC-USDT"
	OccurredAt   time.Time       `json:"occurred_at"`
	Payload      json.RawMessage `json:"payload"`
}

// orderCreatedPayload matches the ME consumer's orderCreatedPayload struct.
type orderCreatedPayload struct {
	OrderID       string `json:"order_id"`        // UUID (becomes OS order ID)
	UserID        string `json:"user_id"`         // "MM-001"
	Side          string `json:"side"`            // "BUY" | "SELL"
	OrderType     string `json:"order_type"`      // always "LIMIT" for MM
	Price         string `json:"price"`           // tick-rounded string
	Quantity      string `json:"quantity"`        // lot-rounded string
	ClientOrderID string `json:"client_order_id"` // = LevelID + "-G" + gen (idempotency key)
}

// orderCancelPayload matches the ME consumer's orderCancelPayload struct.
type orderCancelPayload struct {
	OrderID string `json:"order_id"` // ME/OS-assigned UUID for this order
	UserID  string `json:"user_id"`  // "MM-001"
}

// Producer publishes OrderCreated and OrderCancelRequested commands to orders.commands.
type Producer struct {
	writers map[string]*kafkago.Writer // marketID → Writer for that partition
	logger  *zap.Logger
}

// MarketPartition maps a market to its Kafka partition.
type MarketPartition struct {
	MarketID  string
	Partition int
}

// NewProducer creates a Kafka producer for the given market partitions.
func NewProducer(brokers []string, markets []MarketPartition, logger *zap.Logger) *Producer {
	writers := make(map[string]*kafkago.Writer, len(markets))
	for _, m := range markets {
		writers[m.MarketID] = &kafkago.Writer{
			Addr:                   kafkago.TCP(brokers...),
			Topic:                  TopicOrderCommands,
			Balancer:               &kafkago.LeastBytes{},
			WriteTimeout:           10 * time.Second,
			RequiredAcks:           kafkago.RequireAll, // wait for all in-sync replicas
			AllowAutoTopicCreation: false,
		}
	}
	return &Producer{
		writers: writers,
		logger:  logger,
	}
}

// PublishCreate publishes an OrderCreated command for an MM order.
func (p *Producer) PublishCreate(ctx context.Context, marketID string, partition int,
	orderID, clientOrderID, side, price, quantity string) error {

	payload, err := json.Marshal(orderCreatedPayload{
		OrderID:       orderID,
		UserID:        "MM-001",
		Side:          side,
		OrderType:     "LIMIT",
		Price:         price,
		Quantity:      quantity,
		ClientOrderID: clientOrderID,
	})
	if err != nil {
		return fmt.Errorf("marshal OrderCreated payload: %w", err)
	}

	env := CommandEnvelope{
		EventID:      uuid.New().String(),
		EventType:    "OrderCreated",
		EventVersion: 1,
		MarketID:     marketID,
		OccurredAt:   time.Now().UTC(),
		Payload:      payload,
	}

	return p.publish(ctx, marketID, partition, env)
}

// PublishCancel publishes an OrderCancelRequested command.
// orderID must be the ME/OS-assigned UUID (not client_order_id).
func (p *Producer) PublishCancel(ctx context.Context, marketID string, partition int,
	orderID string) error {

	payload, err := json.Marshal(orderCancelPayload{
		OrderID: orderID,
		UserID:  "MM-001",
	})
	if err != nil {
		return fmt.Errorf("marshal OrderCancelRequested payload: %w", err)
	}

	env := CommandEnvelope{
		EventID:      uuid.New().String(),
		EventType:    "OrderCancelRequested",
		EventVersion: 1,
		MarketID:     marketID,
		OccurredAt:   time.Now().UTC(),
		Payload:      payload,
	}

	return p.publish(ctx, marketID, partition, env)
}

// publish serializes and sends a CommandEnvelope to Kafka.
func (p *Producer) publish(ctx context.Context, marketID string, partition int, env CommandEnvelope) error {
	writer, ok := p.writers[marketID]
	if !ok {
		return fmt.Errorf("no Kafka writer configured for market %q", marketID)
	}

	body, err := json.Marshal(env)
	if err != nil {
		return fmt.Errorf("marshal CommandEnvelope: %w", err)
	}

	msg := kafkago.Message{
		Key:       []byte(marketID), // INVARIANT: must equal env.MarketID
		Value:     body,
		Partition: partition,        // explicit partition assignment
	}

	p.logger.Debug("publishing command",
		zap.String("event_type", env.EventType),
		zap.String("market_id", marketID),
		zap.String("event_id", env.EventID),
		zap.Int("partition", partition),
	)

	if err := writer.WriteMessages(ctx, msg); err != nil {
		return fmt.Errorf("kafka write %s to %s: %w", env.EventType, marketID, err)
	}
	return nil
}

// Close flushes and closes all Kafka writers.
func (p *Producer) Close() {
	for market, w := range p.writers {
		if err := w.Close(); err != nil {
			p.logger.Warn("error closing Kafka writer", zap.String("market", market), zap.Error(err))
		}
	}
}
